[tool.poetry]
name = "roboticarm"
version = "0.1.0"
description = "robotic arm planner based on pybullet"
authors = ["AnnexK <roadto3kmmr@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pybullet = "^3.2.5"
numpy = "^1.24.2"
matplotlib = "^3.7.1"
pyserial = "^3.5"
pydantic = "^1.10.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
